name: CI Workflow with Docker and Allure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t spotify-tests .

      - name: Run Tests Inside Docker
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/allure-results:/app/allure-results \
          spotify-tests mvn clean test -Dsurefire.suiteXmlFiles=./testng.xml

      - name: Download Allure CLI
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz \
          && tar -xvzf allure.tgz

      - name: Generate Allure Report
        run: |
          ./allure-2.21.0/bin/allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
